### ISSUE TITLE
Create blocks script issues

### ISSUE THREAD

**Issue by Sklico** [SYMBIO/next-devstack#107]
I noticed several issues while using createBlocks script:

- `const models = require('../../../../../src/models.json');` - bad path to models.json file, it works with `const models = require('../../../../src/models.json');`
- **dist** in paths to templates - in dist folder, there is no data folder, dist in path is wrong
- blockTemplate.tsx.tpl - bad imports and use of non existing files: 
`import { AppContextProps } from '@symbio/headless/dist/types/appContext';
import { OmitRefType } from '@symbio/headless/dist/types/app';`

**Comment by vonschau** [comment]
Fixed in [v1.0.0-canary.118]
